"""Criando tabelas de usuario e cliente

Revision ID: b82214e00524
Revises: fcff6fe843f3
Create Date: 2026-05-04 20:01:37.013881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82214e00524'
down_revision: Union[str, Sequence[str], None] = 'fcff6fe843f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nome_do_Cliente', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Telefone', sa.String(), nullable=True),
    sa.Column('IMEI', sa.String(), nullable=True),
    sa.Column('Data_venda', sa.Date(), nullable=True),
    sa.Column('Data_vencimento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('clientes')
    # ### end Alembic commands ###
